---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - name: updating repositories
    shell: 
      cmd: apt update -y
   
  - name: installing  java
    apt:
      update_cache: yes
      name: openjdk-8-jdk 
      state: present

  - name: adding jenkins repositories
    shell:
      cmd: wget -q -O -  https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -

  - name: adding jenkins repositories1
    shell: 
      cmd: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  
  - name: updating repositories
    shell:
      cmd: apt update -y
  
  - name: install jenkins 
    apt: 
      name: jenkins
      state: present
  
  - name: restarting jenkins service
    service: 
      name: jenkins
      state: restarted
